CC = gcc
LANG_STD = -std=gnu17
CFLAGS = -Wall -Wfatal-errors

acceptTest : acceptTest.c
	$(CC) $(CFLAGS) $(LANG_STD) acceptTest.c -o acceptTest

listenTest : listenTest.c
	$(CC) $(CFLAGS) $(LANG_STD) listenTest.c -o listenTest

connectTo : connectTo.c
	$(CC) $(CFLAGS) $(LANG_STD) connectTo.c -o connectTo

	